FizzBuzzShashwat.java
CodeToExpress/dailycodebase pull request #332
Opened 2020-09-21 19:47 UTC by shashwatxdevelop

Please make sure you have done the following:

- [ ] Created a folder with the name of language you code inside `/Day<n>/` directory (Where n is for nth day)
- [ ] Added your Codes
- [ ] Tested your codes
- [ ] Added credits (author and date) at the top of the code
- [ ] Updated README.md
- [ ] Added yourself as a contributor using `all-contributors-cli`

2020-09-22 19:04 UTC, shashwatxdevelop commented
This is my Day 2 of java code.

2020-09-25 00:06 UTC, aaditkamat requested changes
Can you split your solutions into seperate PRs based on the day? Also you have added a duplicate Java file in the root of the repository for your Day 1 solution.

2020-09-25 16:46 UTC, shashwatxdevelop commented
> Can you split your solutions into seperate PRs based on the day? Also you have added a duplicate Java file in the root of the repository for your Day 1 solution.

Hey! I am really sorry but I am a beginner in github. I don't know how to separate the PRs. Can you guide me through it please?

2020-09-26 01:40 UTC, aaditkamat commented
> Hey! I am really sorry but I am a beginner in github. I don't know how to separate the PRs. Can you guide me through it please?

No problem Shashwat. If you want to do this programmatically, you can try exploring the GitHub project [ghstack](https://github.com/ezyang/ghstack). However, given your level of experience, I would recommend against doing that. Away to do this manually is to checkout different branches from your forked repo's master branch and make changes specific to a particular day in the branch labelled for the day. For example, you could have 3 seperate branches: `day-1`, `day-2` and `day-3` with the solution for the respective day and then send 3 PRs. 

Anyways, from what I see, most people have combined solutions from different days in a single PR, so I'll approve this to save you the trouble. Just make sure to remove the duplicate Java file at the root of the repository.

2020-09-26 17:48 UTC, shashwatxdevelop commented
> > Hey! I am really sorry but I am a beginner in github. I don't know how to separate the PRs. Can you guide me through it please?
> 
> No problem Shashwat. If you want to do this programmatically, you can try exploring the GitHub project [ghstack](https://github.com/ezyang/ghstack). However, given your level of experience, I would recommend against doing that. Away to do this manually is to checkout different branches from your forked repo's master branch and make changes specific to a particular day in the branch labelled for the day. For example, you could have 3 seperate branches: `day-1`, `day-2` and `day-3` with the solution for the respective day and then send 3 PRs.
> 
> Anyways, from what I see, most people have combined solutions from different days in a single PR, so I'll approve this to save you the trouble. Just make sure to remove the duplicate Java file at the root of the repository.

Thank you so much Aadit. I have deleted the file you told DayOneShashwat.java. Please see if it is deleted or not. When I click on the file it shows that this file is deleted. Please check and tell me if its done. If not, I will try it again. Thank you once again!

2020-09-27 01:42 UTC, aaditkamat commented on Day3/Java/HammingDistance1.java
> +				if (s1.charAt(i)== s2.charAt(i))  // checking same character of both strings
This if condition is redundant.
```suggestion
				if (s1.charAt(i)!= s2.charAt(i))  // checking same character of both strings
				   k += 1;
```

2020-09-27 01:42 UTC, aaditkamat commented on Day3/Java/HammingDistance1.java
> +				else
Remove this else condition

2020-09-27 01:43 UTC, aaditkamat commented on Day2/README.md
> +          System.out.println(s1);             // Printing the new reversed string s1
You can remove the print statement for the new reversed string

2020-09-27 01:44 UTC, aaditkamat commented on Day3/README.md
> +				if (s1.charAt(i)== s2.charAt(i))  // checking same character of both strings
You can update the README as per the suggestions for the Java source code file.

2020-09-27 01:46 UTC, aaditkamat requested changes
Thanks for deleting DayOneShashwat.java from the repository root. I've suggested some small changes for your Day2 and Day3 solutions. Other than that, your PR looks good to go!

2020-09-27 14:26 UTC, shashwatxdevelop reviewed
Hello Aadit! I have made the changes told by you. Please check it once and tell me if I have done it right and everything is okay.

2020-09-28 00:59 UTC, aaditkamat requested changes
I have suggested one more change that I missed out in my last review.

2020-09-28 00:59 UTC, aaditkamat commented on Day3/README.md
> +		System.out.println("Hamming Distance is " + k);   // printing the hamming distance
Prints out that Hamming Distance is 1 when the lengths of the strings are unequal in place of displaying an error message. There should be an else clause to handle that case. Sorry I missed that out in my previous review. Do test your code with sample inputs (and perhaps your own test cases) to make sure it matches with the accepted solution.

2020-09-28 17:58 UTC, shashwatxdevelop reviewed
Hello Aadit! I have made the required changes. Please review them. Also I want to ask one thing that from Day 4 should I start making branches or just continue to make a single PR?

2020-09-29 01:32 UTC, aaditkamat requested changes

2020-09-29 01:32 UTC, aaditkamat commented on Day3/Java/HammingDistance1.java
> +		System.out.println("Hamming Distance is 1"); // if both strings are unequal then hamming distance is eaqual to 1
Hamming Distance is undefined for strings of unequal length. You can check the official solution [here](https://github.com/CodeToExpress/dailycodebase/blob/master/Day3/JavaScript/hamming.js).
```suggestion
		System.err.println("Hamming Distance is undefined"); // if both strings are unequal then hamming distance is undefined
```

2020-09-29 01:34 UTC, aaditkamat commented
Hi @shashwatxdevelop, I would recommend making seperate branches from your fork's master for each day's solution and send the PR from each respective branch.

2020-09-29 06:37 UTC, shashwatxdevelop reviewed
I have made the changes in Day 3 code. Please check it.

2020-09-29 06:53 UTC, aaditkamat commented
> I have made the changes in Day 3 code. Please check it.

The comment on the line still says that the Hamming Distance for two strings of unequal length is 1. Please update that.

2020-09-29 16:34 UTC, shashwatxdevelop reviewed
I made the changes in the comment and well as in the day 3 readme file. Please check that.

2020-09-29 23:41 UTC, aaditkamat approved these changes
Excellent! Thank you for contributing.

2020-09-29 23:42 UTC, merged